dremio:
  outputs:
    dev:
      dremio_space: '@user'
      dremio_space_folder: no_schema
      object_storage_source: minio
      object_storage_path: warehouse.dbt
      password: dremio123
      port: 9047
      software_host: dremio
      threads: 1
      type: dremio
      use_ssl: false
      user: dremio
  target: dev

trino:
  outputs:
    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: trino
      password: [password]  # required if method is ldap or kerberos
      database: delta
      host: trino
      port: 8080
      schema: my_schema
      threads: 1
  target: dev