my_project:
  outputs:
    dev:
      dremio_space: 'dbt'
      dremio_space_folder: no_schema
      object_storage_source: minio
      object_storage_path: warehouse.dbt
      password: dremio123
      port: 9047
      software_host: dremio
      threads: 1
      type: dremio
      use_ssl: false
      user: dremio
  target: dev
